### ISSUE TITLE
windows path issue

### ISSUE THREAD

**Issue by shringi** [mixmixmix/learnmachine#2]
KeyError                                  Traceback (most recent call last)
<ipython-input-3-147208002c1c> in <module>
     16 image_size = 64  # in pixels
     17 number_of_classes = 2 #2-6 - normal blobs. 7-11 more difficult
---> 18 problem = generateBlobsData(imageDir, number_of_classes, number_of_samples, image_size, noiseSize=20)

~\OneDrive - Indian Institute of Science\Side\2020-03 Machine-Learning Mix\tasks\utils\practice_data.py in generateBlobsData(imageDir, noClasses, trainSamples, imSize, noiseSize, colour)
     98         print(blob_file)
     99         blob_class = blob_file.split("/")[-1].split("_")[0]
--> 100         blob_class_int=intblobclass[blob_class]
    101         if(noClasses <= blob_class_int):
    102             continue

KeyError: 'simple'

**Comment by mixmixmix** [comment]
Now using `os.sep` for system independent path separator. https://github.com/mixmixmix/learnmachine/commit/59495051f875c5346a02e65d328f49cc4ae15623
